version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "cd into tailwind-site and install"
      - cd tailwind-site
      - npm ci --legacy-peer-deps
      - node -v
      - npm -v

  build:
    commands:
      - echo "Building app in tailwind-site"
      - cd tailwind-site    # safe if build is started from root; harmless if already in subdir
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: tailwind-site/dist
  discard-paths: no