version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo "Moving into app directory"
      - cd portfolioV2/tailwind-site
      - npm ci

  build:
    commands:
      - echo "Building Vite app"
      - npm run build

artifacts:
  files:
    - '**/*'
  base-directory: tailwind-site/dist
  discard-paths: no